import json, os, zipfile
from dataclasses import dataclass, asdict
from typing import List, Dict

# semisplit models from v63 script

def count_points_F3(a: int, b: int, c: int) -> int:
    cnt = 1
    for x in range(3):
        rhs = (x**3 + a*x*x + b*x + c) % 3
        for y in range(3):
            if (y*y - rhs) % 3 == 0:
                cnt += 1
    return cnt


def semisplit_models() -> List[Dict[str, int]]:
    out = []
    for a in (1, 2):
        for b in (0, 1, 2):
            for c in (0, 1, 2):
                disc = (-a**3 * c + a*a*b*b - b**3) % 3
                if disc == 0:
                    continue
                roots = [r for r in (0, 1, 2) if (r**3 + a*r*r + b*r + c) % 3 == 0]
                if len(roots) != 1:
                    continue
                r = roots[0]
                out.append({
                    "alpha": a,
                    "beta": b,
                    "gamma": c,
                    "root": r,
                    "disc_const": disc,
                    "E_F3_order": count_points_F3(a, b, c),
                })
    return out

@dataclass
class QuotientAnalysis:
    alpha: int
    beta: int
    gamma: int
    root: int
    E_F3_order: int
    upstairs_surface: str
    quotient_surface: str
    fixed_points: int
    quotient_singularity_type: str
    quotient_picard_rank: int
    quotient_intersection_matrix: List[List[int]]
    quotient_basis: List[str]
    canonical_class_in_basis: List[int]
    anticanonical_square: int
    anticanonical_nef: bool
    anticanonical_ample: bool
    fiber_square: int
    bisection_square: int
    fiber_bisection_intersection: int
    has_minus_one_class_in_generated_lattice: bool
    mmp_obstruction: str
    resolution_euler: int
    resolution_picard_rank: int
    resolution_K2: int
    verdict: str


def analyze_model(row: Dict[str, int]) -> QuotientAnalysis:
    # Basis on S = E x P1_u:
    # U = class of {pt} x P1, V = class of E x {pt}, with U^2=V^2=0, U.V=1.
    # Under quotient q by g=(-P+T,-u):
    # q^*B = U_O + U_T ~ 2U,  q^*F = V_u + V_{-u} ~ 2V.
    # Therefore B^2=0, F^2=0, B.F=2.
    # K_S = p2^*K_{P1} = -2V = -q^*F, so K_Q = -F.
    return QuotientAnalysis(
        alpha=row['alpha'], beta=row['beta'], gamma=row['gamma'], root=row['root'], E_F3_order=row['E_F3_order'],
        upstairs_surface="E x P1_u with diagonal involution g(P,u)=(-P+T,-u)",
        quotient_surface="Q=(E x P1_u)/<g>, t=u^2",
        fixed_points=8,
        quotient_singularity_type="8 x A1",
        quotient_picard_rank=2,
        quotient_intersection_matrix=[[0,2],[2,0]],
        quotient_basis=["F (genus-one fiber over t)", "B (image of O union T bisection)"],
        canonical_class_in_basis=[-1,0], # K = -F + 0*B
        anticanonical_square=0,
        anticanonical_nef=True,
        anticanonical_ample=False,
        fiber_square=0,
        bisection_square=0,
        fiber_bisection_intersection=2,
        has_minus_one_class_in_generated_lattice=False,
        mmp_obstruction=(
            "In the rank-2 descended lattice generated by F and B, every class D=aF+bB has D^2=4ab, "
            "so there is no class with square -1. Moreover -K_Q=F is nef with F^2=0, hence not ample."
        ),
        resolution_euler=12,
        resolution_picard_rank=10,
        resolution_K2=0,
        verdict=(
            "This semisplit quotient presentation is a rational genus-one surface with 8 A1 quotient points, "
            "but it is not already a del Pezzo: -K is the fiber class, nef with square 0, and the descended rank-2 lattice "
            "contains no -1 class to start an additional birational contraction within this presentation."
        )
    )


def main():
    models = semisplit_models()
    analyses = [analyze_model(m) for m in models]
    summary = {
        "models_scanned": len(analyses),
        "all_same_picard_rank": len({a.quotient_picard_rank for a in analyses}) == 1,
        "all_same_intersection_matrix": len({tuple(tuple(r) for r in a.quotient_intersection_matrix) for a in analyses}) == 1,
        "all_anticanonical_not_ample": all(not a.anticanonical_ample for a in analyses),
        "all_no_minus_one_in_generated_lattice": all(not a.has_minus_one_class_in_generated_lattice for a in analyses),
        "headline": (
            "The v63 semisplit quotient presentation fixes the local cone problem, but the quotient itself has Picard rank 2, "
            "intersection lattice [[0,2],[2,0]], canonical class K=-F, and therefore -K nef with square 0 rather than ample. "
            "So this presentation does not itself realize a del Pezzo surface with rho=1."
        ),
        "models": [asdict(a) for a in analyses],
    }

    outdir = "/mnt/data/v64_work"
    os.makedirs(outdir, exist_ok=True)
    json_path = os.path.join(outdir, "i0iv_quotient_mmp_analyzer_v64.json")
    md_path = os.path.join(outdir, "i0iv_quotient_mmp_analyzer_v64.md")
    py_path = os.path.join(outdir, "i0iv_quotient_mmp_analyzer_v64.py")

    with open(json_path, "w") as f:
        json.dump(summary, f, indent=2)

    md = []
    md.append("# v64 quotient/MMP analyzer for the semisplit `I0* + I0*` quotient branch\n")
    md.append("## Headline\n")
    md.append(summary['headline'] + "\n")
    md.append("## Core divisor-lattice computation\n")
    md.append("On the smooth product `S = E × P1_u`, write:\n")
    md.append("- `U = [{pt} × P1_u]`\n")
    md.append("- `V = [E × {pt}]`\n")
    md.append("with intersection form `U^2 = V^2 = 0`, `U·V = 1`.\n")
    md.append("For the semisplit quotient `q : S -> Q = S/<g>` with `g(P,u)=(-P+T,-u)`, the natural descended classes are:\n")
    md.append("- `q^*B = U_O + U_T ~ 2U` (image of the exchanged zero/T sections)\n")
    md.append("- `q^*F = V_u + V_{-u} ~ 2V` (genus-one fiber over `t=u^2`)\n")
    md.append("Hence\n")
    md.append("```\n")
    md.append("B^2 = 0,   F^2 = 0,   B·F = 2.\n")
    md.append("```\n")
    md.append("so the quotient intersection matrix in basis `(F,B)` is\n")
    md.append("```\n")
    md.append("[[0,2],\n [2,0]].\n")
    md.append("```\n")
    md.append("The canonical class on the product is `K_S = -2V`, and since the quotient is quasi-etale in codimension 1,\n")
    md.append("```\n")
    md.append("K_Q = -F.\n")
    md.append("```\n")
    md.append("Therefore\n")
    md.append("```\n")
    md.append("(-K_Q)^2 = F^2 = 0,\n")
    md.append("```\n")
    md.append("so `-K_Q` is nef but **not ample**.\n")
    md.append("## Consequences\n")
    md.append("- The quotient has `8` isolated `A1` points and Picard rank `2`.\n")
    md.append("- Its crepant resolution has Euler number `12`, `K^2 = 0`, and Picard rank `10`.\n")
    md.append("- Inside the descended rank-2 lattice generated by `(F,B)`, every divisor class has square `4ab`, so there is **no class of square -1** in that generated lattice.\n")
    md.append("- Hence this semisplit quotient presentation is **not already a log del Pezzo model**; any route to `rho=1` would need a genuinely different birational presentation or an extra contraction mechanism not visible in this quotient lattice.\n")
    md.append("## Models checked\n")
    for a in analyses:
        md.append(f"- `(alpha,beta,gamma)=({a.alpha},{a.beta},{a.gamma})`, root `{a.root}`, `#E(F3)={a.E_F3_order}`: same quotient lattice and same obstruction.\n")

    with open(md_path, "w") as f:
        f.write("\n".join(md))

    # save script copy
    with open(py_path, "w") as f:
        f.write(open(__file__).read())

    zip_path = "/mnt/data/projective_higher_dim_tools_v64_quotient_mmp_analyzer.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(md_path, arcname=os.path.basename(md_path))
        zf.write(json_path, arcname=os.path.basename(json_path))
        zf.write(py_path, arcname=os.path.basename(py_path))

    print(json.dumps({
        "zip": zip_path,
        "md": md_path,
        "json": json_path,
        "script": py_path,
        "models": len(analyses)
    }, indent=2))

if __name__ == "__main__":
    main()
